# Generated by Django 6.0.3 on 2026-03-23 16:47

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogcategory_description_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='description',
            field=models.TextField(blank=True, help_text='Optional short description of this category'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(help_text='URL friendly version e.g betting-tips', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='blogdetailpage',
            name='banner_image',
            field=models.ForeignKey(blank=True, help_text='Main image shown at top of post and on listing cards', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='blogdetailpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('quote', 3), ('embed', 4), ('raw_html', 5)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'help_text': 'Add a heading or subheading'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'h4', 'bold', 'italic', 'underline', 'strikethrough', 'ol', 'ul', 'hr', 'link', 'image', 'embed', 'blockquote', 'code'], 'help_text': 'Add your main text content here'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Insert a full width standalone image'}), 3: ('wagtail.blocks.BlockQuoteBlock', (), {'help_text': 'Add a highlighted pull quote'}), 4: ('wagtail.blocks.URLBlock', (), {'help_text': 'Paste a YouTube, Twitter or video URL to embed'}), 5: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Add custom HTML if needed', 'required': False})}),
        ),
        migrations.AlterField(
            model_name='blogdetailpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Select categories for this post', to='blog.blogcategory'),
        ),
        migrations.AlterField(
            model_name='blogdetailpage',
            name='intro',
            field=models.CharField(help_text='Short summary shown on blog listing page', max_length=300),
        ),
        migrations.AlterField(
            model_name='blogindexpage',
            name='intro',
            field=models.TextField(blank=True, help_text='Intro text shown at top of blog listing page'),
        ),
    ]
