# Generated by Django 6.0.3 on 2026-03-23 17:03

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogcategory_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('quote', 3), ('embed', 4), ('raw_html', 5)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'help_text': 'Add a heading or subheading'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'underline', 'strikethrough', 'ol', 'ul', 'hr', 'link', 'image', 'embed', 'blockquote', 'code'], 'help_text': 'Add your main text content here'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Insert a full width standalone image'}), 3: ('wagtail.blocks.BlockQuoteBlock', (), {'help_text': 'Add a highlighted pull quote'}), 4: ('wagtail.blocks.URLBlock', (), {'help_text': 'Paste a YouTube, Twitter or video URL to embed'}), 5: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Add custom HTML if needed', 'required': False})}),
        ),
    ]
