# Generated by Django 6.0.3 on 2026-04-16 18:02

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogdetailpage_body'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='banner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='blogdetailpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='blog.blogcategory'),
        ),
        migrations.AlterField(
            model_name='blogdetailpage',
            name='intro',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='blogindexpage',
            name='intro',
            field=models.TextField(blank=True),
        ),
    ]
