# Generated by Django 6.0.3 on 2026-03-18 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BettingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
            ],
            options={
                'verbose_name_plural': 'Betting Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookingCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('booking_code', models.CharField(max_length=200)),
                ('accumulated_odds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.bettingcompany')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
