# Generated by Django 6.0.3 on 2026-03-29 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('booking_code', models.CharField(max_length=200)),
                ('accumulated_odds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan', models.CharField(choices=[('safe', 'Safe Odds (1.6 - 2.5)'), ('high', 'High Odds (2.0 - 3.0)'), ('both', 'Both Plans')], default='both', help_text='Which subscription plan can see this code', max_length=10)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.bettingcompany')),
            ],
            options={
                'verbose_name': 'VIP Code',
                'verbose_name_plural': 'VIP Codes',
                'ordering': ['-date'],
            },
        ),
    ]
