# Generated by Django 6.0.3 on 2026-05-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='bettingcompany',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL friendly name e.g sportybet-booking-codes', max_length=100, null=True, unique=True),
        ),
    ]
