# Generated by Django 6.0.3 on 2026-05-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_bettingcompany_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectWinPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('match', models.CharField(help_text='e.g Arsenal vs Chelsea', max_length=200)),
                ('tip', models.CharField(help_text='e.g Home Win, Over 2.5, BTTS', max_length=200)),
            ],
            options={
                'verbose_name': 'Direct Win Prediction',
                'verbose_name_plural': 'Direct Win Predictions',
                'ordering': ['-date'],
            },
        ),
    ]
