# Generated by Django 6.0.3 on 2026-08-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_delete_prediction_partner_description_partner_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='directwinprediction',
            name='analysis',
            field=models.TextField(blank=True, help_text='Write your match analysis here'),
        ),
    ]
